modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="accurs"
version="1.0.1"
displayName="Accurs"
credits="Sayln Inc"
displayURL="https://github.com/Sohom829/AccursMod"
authors="Sohom829, Sayln"
description='''
New ores, tools, biomes, dimensions, foods, items, enhanments 
'''

[[dependencies.accurs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




